Repository pyiron/pyiron, pull requests merged in 2020-11, with the labels that each got.

#1130 Test Python 3.9
  azure-pipelines.yml
Labels: enhancement

#1133 Lammps Structure raise ValueError
  pyiron/lammps/structure.py
Labels: Lammps, enhancement

#1135 pyiron table: Remove the annoying warning
  pyiron/table/datamining.py
  tests/table/test_datamining.py
Labels: enhancement

#1136 Update travis links to travis.com
  README.rst
Labels: enhancement

#1137 Travis: Combine all tests in one stage
  .travis.yml
Labels: enhancement

#1139 Build Documentation and Docs on Azure
  .ci_support/azure-unix-test-template.yml
  .ci_support/build_docs.sh
  .ci_support/build_notebooks.sh
  .ci_support/environment-docs.yml
  .ci_support/environment.yml
  .ci_support/test_backwards.sh
  .ci_support/travis_build_docs.sh
  .ci_support/travis_setup_notebooks.sh
  .ci_support/travis_setup_pyiron.sh
  .github/workflows/backwards.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
  .github/workflows/unittests.yml
  .travis.yml
  appveyor.yml
  azure-pipelines.yml
Labels: bug, urgent

#1120 Get neighbors by distance
  notebooks/water_MD.ipynb
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#1149 spin setter removed if not implemented
  pyiron/atomistics/job/interactive.py
Labels: bug, urgent

#1146 scaled positions changed to positions
  pyiron/atomistics/job/interactive.py
Labels: AtomisticStructure, bug, urgent

#1142 Scipy unit
  pyiron/interactive/scipy_minimizer.py
  tests/interactive/test_scipyminimizer.py
Labels: bug, enhancement

#1154 add return_indices in get_extended_positions
  pyiron/atomistics/structure/atoms.py
Labels: enhancement

#1152 Lammps: Fix non periodic boundaries in input
  pyiron/lammps/base.py
Labels: Lammps

#1159 [ci skip] Update old syntax of importing Project in tutorials notebooks
  notebooks/bandstructure.ipynb
  notebooks/first_steps.ipynb
  notebooks/hcp_workfunction.ipynb
  notebooks/phonopy_example.ipynb
  notebooks/structures.ipynb
  notebooks/water_MD.ipynb
Labels: priority: low

#1158 get wrapped positions created
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: AtomisticStructure, enhancement, priority: low

#1164 Add friendly error message on missing potential
  pyiron/atomistics/job/potentials.py
Labels: Lammps, enhancement

#1163 Find mic
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: AtomisticStructure, enhancement, priority: low

#1151 Convergence check NELM=1
  pyiron/vasp/base.py
Labels: VASP

#1170 Fix neighbors
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: AtomisticStructure, bug

#1171 Debug no neigh
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: AtomisticStructure, priority: critical

#1160 replace ase get_distances_array
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: AtomisticStructure, enhancement, priority: low

#1082 Extend pyscal interface
  .ci_support/environment.yml
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/ovito.py
  pyiron/atomistics/structure/pyscal.py
  tests/atomistics/structure/test_pyscal.py
Labels: enhancement

#1095 SciPyMinimizer: Keep default values from self.input
  pyiron/interactive/scipy_minimizer.py
Labels: enhancement

#1194 [minor] add new line in spins.in
  pyiron/sphinx/base.py
Labels: S/PHI/nX, enhancement, priority: low

#1185 Revamped neighbor class
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_neighbors.py
Labels: AtomisticStructure, enhancement, priority: low

#1196 Add check that reference job is static
  pyiron/atomistics/master/phonopy.py
  tests/atomistics/master/test_phonopy.py
Labels: enhancement

#1079 Elastic tensor class
  .ci_support/environment.yml
  pyiron/__init__.py
  pyiron/atomistics/master/elastic.py
  tests/atomistics/master/test_elastic.py
Labels: AtomisticStructure, enhancement, priority: medium

#1205 [ci skip] Fix a typo: PostgeSQL-->PostgreSQL in installation.rst
  docs/source/installation.rst
Labels: priority: low

#1204 Bugfix get neighbors
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_neighbors.py
Labels: AtomisticStructure, bug, priority: low

#1207 Inherit from PyironFactory
  pyiron/atomistics/structure/factory.py
Labels: AtomisticStructure, enhancement

#1202 Update to pyscal to 2.10.3
  .ci_support/environment.yml
  pyiron/atomistics/structure/pyscal.py
  tests/atomistics/structure/test_pyscal.py
Labels: bug

#1208 K mesh ang
  pyiron/dft/job/generic.py
  pyiron/gpaw/gpaw.py
  pyiron/sphinx/base.py
  pyiron/vasp/base.py
  tests/sphinx/test_base.py
  tests/vasp/test_vasp_import.py
Labels: GPAW, S/PHI/nX, VASP, enhancement

#1213 Move pyiron table to pyiron_base
  .ci_support/environment.yml
  pyiron/project.py
  pyiron/table/datamining.py
  setup.py
Labels: enhancement

#1216 Pyscal fixes
  binder/environment.yml
  pyiron/atomistics/structure/pyscal.py
  pyiron/table/funct.py
  tests/atomistics/structure/test_pyscal.py
Labels: enhancement

#1217 Update remaining tests to Python 3.9
  .github/workflows/backwards.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/docs.yml
  .github/workflows/notebooks.yml
Labels: enhancement

#1211 Get layers and add `Analyse`
  pyiron/atomistics/structure/analyse.py
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_analyse.py
Labels: AtomisticStructure, enhancement, priority: medium

#1215 Interface method use pyscal
  pyiron/thermodynamics/interfacemethod.py
Labels: enhancement

#1223 pyscal return numpy arrays
  pyiron/atomistics/structure/pyscal.py
Labels: enhancement

#1220 Cluster neighbors
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_neighbors.py
Labels: AtomisticStructure, enhancement, priority: low

#1212 Interface to lammps move
  pyiron/lammps/control.py
  tests/lammps/test_control.py
Labels: Lammps, enhancement

#1228 Warn users about combining Lammps interactive and langevin
  pyiron/lammps/interactive.py
Labels: Lammps

#1235 pyiron base update to 0.1.36
  .ci_support/environment.yml
  setup.py
Labels: enhancement
