Repository pyiron/pyiron, pull requests merged in 2020-09, with the labels that each got.

#926 :bug: in `calc_minimize`
  pyiron/vasp/base.py
  tests/vasp/test_vasp.py
Labels: bug

#928 Support CONDA_DIR in addition to CONDA_PREFIX
  pyiron/lammps/potential.py
  pyiron/sphinx/potential.py
Labels: enhancement

#933 Vasp potential peeking
  pyiron/vasp/base.py
  pyiron/vasp/potential.py
  tests/vasp/test_potential.py
Labels: enhancement

#937 Update to Sphinx 2.7.0
  .ci_support/environment-notebooks.yml
  binder/environment.yml
Labels: enhancement

#938 Update pysqa dependence
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#920 Job core
  docs/source/hdf5.rst
  pyiron/base/generic/hdfio.py
  pyiron/base/job/generic.py
  pyiron/base/master/generic.py
Labels: enhancement

#943 :memo: Update water MD tutorial
  notebooks/water_MD.ipynb
Labels: enhancement

#948 Copy files when importing calculations - optional
  pyiron/project.py
Labels: enhancement

#949 Store import_directory in HDF5 file
  pyiron/base/job/generic.py
  tests/vasp/test_vasp_import.py
Labels: enhancement

#945 Vasprun fix
  pyiron/vasp/base.py
  pyiron/vasp/vasprun.py
  tests/static/vasp_test_files/full_job_minor_glitch/CONTCAR
  tests/static/vasp_test_files/full_job_minor_glitch/POSCAR
  tests/static/vasp_test_files/full_job_minor_glitch/POTCAR
  tests/static/vasp_test_files/full_job_minor_glitch/vasprun.xml
  tests/static/vasp_test_files/vasprun_samples/vasprun_8.xml
  tests/vasp/test_vasp_import.py
  tests/vasp/test_vasprun.py
Labels: enhancement

#954 Travis fix
  .travis.yml
  tests/vasp/test_vasp_import.py
Labels: bug

#972 Append atoms
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#974 Apply strain bugfix
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: bug

#975 Use default potential
  pyiron/lammps/base.py
  tests/lammps/test_base.py
Labels: enhancement

#976 Remove remove_jobs() from notebooks
  notebooks/bandstructure.ipynb
  notebooks/data_mining.ipynb
  notebooks/energy_volume_curve.ipynb
  notebooks/gamma_surface_parallel_master.ipynb
  notebooks/lammps-fe-c-example.ipynb
  notebooks/phonopy_example.ipynb
  notebooks/sqs.ipynb
  notebooks/test_pyiron_installation.ipynb
  notebooks/tests_sphinx_sphinx_check_all.ipynb
Labels: enhancement

#977 Changed kpoints per reciprocal angstrom
  pyiron/dft/job/generic.py
Labels: enhancement

#978 phonopy notebook updated to replace scale function by pyiron function
  notebooks/phonopy_example.ipynb
Labels: enhancement

#980 phonopy spins added
  pyiron/atomistics/master/phonopy.py
  tests/atomistics/master/test_phonopy.py
Labels: bug

#985 Update to pyiron_base 0.1.16
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#983 change jobs names for child jobs in phonopy
  pyiron/atomistics/master/phonopy.py
  pyiron/testing/randomatomistic.py
  tests/atomistics/master/test_phonopy.py
Labels: code_smell, enhancement

#989 flexible formats for force constants in HessianJob
  pyiron/thermodynamics/hessian.py
  tests/thermodynamics/__init__.py
  tests/thermodynamics/test_hessianJob.py
Labels: bug, enhancement

#991 Implement default interactive interface
  pyiron/testing/randomatomistic.py
Labels: enhancement

#990 Discuss changes to the hessian class
  pyiron/thermodynamics/hessian.py
  tests/atomistics/master/test_murnaghan.py
  tests/atomistics/master/test_phonopy.py
  tests/interactive/test_scipyminimizer.py
  tests/thermodynamics/__init__.py
  tests/thermodynamics/test_hessianJob.py
Labels: enhancement

#994 test murnaghan convergence
  tests/atomistics/master/test_murnaghan.py
Labels: enhancement

#996 Remove import dir from HDF5
  pyiron/project.py
Labels: bug

#1000 Pyiron table add get_enery_pot
  pyiron/table/datamining.py
  pyiron/table/funct.py
Labels: enhancement

#1002 Implement total energy for gpaw
  pyiron/gpaw/pyiron_ase.py
Labels: enhancement

#918 Vasp parsing
  .ci_support/azure-unix-test-template.yml
  pyiron/vasp/base.py
  pyiron/vasp/oszicar.py
  tests/static/vasp_test_files/oszicar_samples/OSZICAR_1
  tests/static/vasp_test_files/oszicar_samples/OSZICAR_2
  tests/table/test_datamining.py
  tests/vasp/test_oszicar.py
  tests/vasp/test_vasp_import.py
Labels: enhancement

#997 Get global shells
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#1001 Reform get neighbors
  notebooks/water_MD.ipynb
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  pyiron/lammps/structure.py
  tests/atomistics/structure/test_atoms.py
Labels: code_smell, enhancement
