Repository pyiron/pyiron, pull requests merged in 2020-08, with the labels that each got.

#817 safer behaviour for remove_jobs
  pyiron/base/project/generic.py
Labels: enhancement

#680 A new `Atoms` class derived from `ase`
  notebooks/water_MD.ipynb
  pyiron/atomistics/master/phonopy.py
  pyiron/atomistics/structure/atom.py
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/generator.py
  pyiron/atomistics/structure/pyironase.py
  pyiron/gpaw/gpaw.py
  pyiron/project.py
  pyiron/quickff/quickff.py
  pyiron/yaff/yaff.py
  tests/atomistics/structure/test_atom.py
  tests/atomistics/structure/test_atoms.py
  tests/lammps/test_base.py
Labels: enhancement, help wanted

#823 Remove DFT functions from AtomisticJob
  pyiron/atomistics/job/atomistic.py
  pyiron/dft/job/generic.py
Labels: enhancement

#827 Remove atom color
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/periodic_table.py
Labels: enhancement

#813 Add SQSgenerator class
  .ci_support/environment-notebooks.yml
  binder/environment.yml
  notebooks/sqs.ipynb
  pyiron/atomistics/job/sqs.py
  pyiron/base/job/jobtype.py
Labels: enhancement

#840 Support more properties directly from mendeleev
  pyiron/atomistics/structure/periodic_table.py
Labels: enhancement

#837 Update flush frequency
  pyiron/base/job/interactive.py
Labels: enhancement

#824 Adding a code of conduct
  CODE_OF_CONDUCT.md
Labels: enhancement

#841 Add gamma surface example
  notebooks/gamma_surface_parallel_master.ipynb
Labels: enhancement

#842 Execute interactive master jobs in the background
  pyiron/base/master/parallel.py
Labels: enhancement

#844 Pipeline
  pyiron/atomistics/master/parallel.py
  pyiron/base/master/parallel.py
Labels: enhancement

#847 fix interactive master in non modal mode
  pyiron/atomistics/master/murnaghan.py
  pyiron/atomistics/master/phonopy.py
Labels: enhancement

#852 cli wrapper PEP8 clean up
  pyiron/cli/wrapper.py
Labels: enhancement

#849 Database functions get_job_status and set_job_status
  pyiron/base/database/filetable.py
  pyiron/base/database/generic.py
  pyiron/base/database/jobtable.py
  pyiron/base/job/generic.py
  pyiron/base/job/jobstatus.py
  pyiron/base/master/flexible.py
  pyiron/base/master/parallel.py
  pyiron/base/master/serial.py
  pyiron/base/project/generic.py
Labels: enhancement

#851 Delete database entry if HDF5 does not exist
  pyiron/base/job/jobtype.py
  pyiron/base/server/queuestatus.py
Labels: enhancement

#850 Enable local database for pyiron installations without a database
  pyiron/base/job/generic.py
  pyiron/base/job/wrapper.py
  pyiron/base/project/generic.py
  pyiron/base/settings/generic.py
Labels: enhancement

#855 create_job deletes jobs
  pyiron/base/job/jobtype.py
Labels: bug

#853 Fixes for server logger
  pyiron/base/server/generic.py
Labels: bug

#854 filetable - enforce job_id to be int
  pyiron/base/database/filetable.py
Labels: bug

#848 pyiron without database
  pyiron/base/database/filetable.py
  pyiron/base/job/generic.py
  pyiron/base/job/wrapper.py
  pyiron/base/project/generic.py
  pyiron/base/server/queuestatus.py
Labels: enhancement

#833 check if potential supports correct elements
  pyiron/lammps/base.py
  tests/lammps/test_base.py
Labels: enhancement

#859 reset pandas display options w/o full_table
  pyiron/base/database/filetable.py
  pyiron/base/database/jobtable.py
Labels: bug

#858 pyiron atoms changed to pbc when not specified
  pyiron/atomistics/job/interactive.py
Labels: invalid

#868 Fix GenericMaster append
  pyiron/base/master/generic.py
Labels: enhancement

#867 Fix queue_check_job_is_waiting_or_running()
  pyiron/base/job/generic.py
  pyiron/base/project/generic.py
Labels: bug

#865 fix wait for job
  pyiron/base/server/queuestatus.py
Labels: enhancement

#862 Fix refine_cell() and get_primitive_cell()
  pyiron/atomistics/structure/atoms.py
Labels: bug

#861 VASP always return periodic cells
  pyiron/vasp/structure.py
  pyiron/vasp/vasprun.py
  tests/vasp/test_structure.py
Labels: bug

#871 local datbase fixes
  pyiron/base/project/generic.py
  pyiron/base/settings/generic.py
Labels: bug

#873 Structurelist
  notebooks/structures.ipynb
  pyiron/atomistics/job/atomistic.py
  pyiron/atomistics/job/structurecontainer.py
  tests/atomistics/job/test_StructureContainer.py
Labels: enhancement

#892 small bugfix
  pyiron/sphinx/base.py
Labels: bug

#893 Fix Bug in FlexibleMaster
  pyiron/base/master/flexible.py
Labels: bug

#883 require user input in `remove_jobs` + create `remove_jobs_silently`
  notebooks/bandstructure.ipynb
  notebooks/data_mining.ipynb
  notebooks/energy_volume_curve.ipynb
  notebooks/gamma_surface_parallel_master.ipynb
  notebooks/lammps-fe-c-example.ipynb
  notebooks/phonopy_example.ipynb
  notebooks/sqs.ipynb
  notebooks/test_pyiron_installation.ipynb
  notebooks/tests_sphinx_sphinx_check_all.ipynb
  pyiron/base/project/generic.py
  pyiron/cli/rm.py
  tests/atomistics/job/test_atomistic.py
  tests/atomistics/master/test_murnaghan.py
  tests/atomistics/master/test_murnaghan_master_modal.py
  tests/atomistics/master/test_murnaghan_non_modal.py
  tests/atomistics/structure/test_pyscal.py
  tests/base/job/test_childids.py
  tests/base/project/test_projectPath.py
  tests/interactive/test_scipyminimizer.py
  tests/interactive/test_sxextoptint.py
  tests/lammps/test_base.py
  tests/lammps/test_interactive.py
  tests/quickff_module/test_quickff.py
  tests/table/test_datamining.py
  tests/test_project.py
  tests/testing/test_exampleJob_non_modal.py
  tests/testing/test_serialMaster.py
  tests/testing/test_serialMaster_non_modal.py
  tests/vasp/test_vasp.py
  tests/vasp/test_vasp_import.py
  tests/yaff_module/test_yaff.py
Labels: enhancement

#895 Update control.py
  pyiron/lammps/control.py
Labels: bug, enhancement

#903 Learning commit
  tests/lammps/test_base.py
Labels: enhancement

#904 Increase precision in POSCAR
  pyiron/vasp/structure.py
Labels: bug

#905 Fix wait_for_job
  pyiron/base/server/queuestatus.py
Labels: bug

#898 Accelerate pyiron table
  pyiron/table/datamining.py
Labels: enhancement

#908 Simplify setting potentials for VASP
  pyiron/vasp/base.py
  pyiron/vasp/potential.py
Labels: enhancement

#911 Fix selective dynamics
  pyiron/atomistics/structure/atoms.py
Labels: bug

#912 Support multiple cluster
  pyiron/base/database/filetable.py
  pyiron/base/project/generic.py
  pyiron/base/settings/generic.py
Labels: enhancement

#919 Fix copy_to()
  pyiron/base/job/core.py
  pyiron/base/job/generic.py
Labels: bug
