Repository pyiron/pyiron, pull requests merged in 2020-05, with the labels that each got.

#634 applied numpy array for all coordinates in k points
  pyiron/sphinx/base.py
  tests/sphinx/test_base.py
Labels: bug

#507 Update pyscal interface
  pyiron/atomistics/structure/pyscal.py
Labels: enhancement

#642 Fix sphinx version for mybinder
  binder/environment.yml
Labels: bug

#645 new create_hkl_surface function
  pyiron/atomistics/structure/generator.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#496 Rotate pressures
  pyiron/lammps/base.py
  pyiron/lammps/control.py
  pyiron/lammps/interactive.py
  tests/lammps/test_base.py
Labels: bug

#650 Making sure vasp runs only 1 ionic step for a static calculation
  pyiron/vasp/base.py
Labels: bug

#647 phonopy updated to circumvent all deprecation warnings
  pyiron/atomistics/master/phonopy.py
Labels: enhancement

#649 Bug in VASP parsing from OUTCAR
  pyiron/vasp/base.py
Labels: bug

#587 Fix displacements
  pyiron/atomistics/job/atomistic.py
  tests/atomistics/job/test_atomistic.py
  tests/vasp/test_vasp_import.py
Labels: bug

#656 calc_md with pressure 0 corrected
  pyiron/lammps/control.py
  tests/lammps/test_base.py
Labels: bug

#659 Use alphabetical sorting for job types
  pyiron/base/job/jobtype.py
Labels: enhancement

#458 Planar avg
  pyiron/atomistics/volumetric/generic.py
  tests/atomistics/volumetric/test_volumetric_data.py
Labels: enhancement

#658 Add HessianJob for thermodynamic integration
  pyiron/base/job/jobtype.py
  pyiron/thermodynamics/hessian.py
Labels: enhancement

#667 pylammpsmpi clean up
  pyiron/lammps/interactive.py
  pyiron/lammps/sub/__init__.py
  pyiron/lammps/sub/lmpmpi.py
Labels: enhancement

#567 add methods to get charges/ids for pair_style full
  pyiron/lammps/potential.py
  pyiron/lammps/structure.py
Labels: enhancement

#525 small bugfix when set_repeat is applied after get_initial_magnetic_mo…
  pyiron/atomistics/structure/atoms.py
Labels: bug

#356 VASP: "ZBRENT: fatal error" capturing
  pyiron/vasp/base.py
Labels: bug

#671 Visualization of magnetic moments in plot3d()
  pyiron/atomistics/structure/atoms.py
Labels: enhancement

#666 Fix error message when calc_* is set before structure
  pyiron/lammps/base.py
  pyiron/lammps/control.py
Labels: enhancement

#675 Simplify Python only jobs
  pyiron/base/job/generic.py
Labels: enhancement

#676 Update create_object() to support custom classes
  pyiron/base/generic/hdfio.py
Labels: enhancement

#678 Use new module interface
  pyiron/base/job/jobtype.py
Labels: enhancement

#679 Create job template
  pyiron/base/job/template.py
Labels: enhancement

#682 fix pyiron table
  pyiron/table/datamining.py
Labels: bug

#670 Update spin tag in structure
  pyiron/dft/job/generic.py
  pyiron/vasp/base.py
  pyiron/vasp/interactive.py
Labels: bug, enhancement

#683 Remove warnings filter
  pyiron/atomistics/structure/atoms.py
Labels: bug

#681 Add Vaspsol support
  pyiron/base/job/jobtype.py
  pyiron/vasp/vaspsol.py
Labels: enhancement

#552 Vasp constrained dynamics
  pyiron/base/generic/parameters.py
  pyiron/base/job/jobtype.py
  pyiron/vasp/metadyn.py
  pyiron/vasp/report.py
  pyiron/vasp/structure.py
  tests/static/vasp_test_files/poscar_samples/POSCAR_metadyn
  tests/vasp/test_vasp.py
Labels: enhancement

#690 Sphinx volumetric data
  pyiron/sphinx/base.py
  pyiron/sphinx/volumetric_data.py
  tests/sphinx/test_base.py
  tests/static/sphinx/sphinx_test_2_5_hdf5/sphinx_test_2_5/relaxedStr.sx
  tests/static/sphinx/sphinx_test_2_5_hdf5/sphinx_test_2_5/rho.sxb
  tests/static/sphinx/sphinx_test_2_5_hdf5/sphinx_test_2_5/vElStat-eV.sxb
Labels: enhancement

#689 Mybinder: update postBuild
  .travis.yml
  binder/postBuild
Labels: enhancement

#695 Add readthedocslink to README
  README.rst
Labels: enhancement

#696 Minor news update
  docs/index.rst
Labels: enhancement

#700 Use stale label
  .github/stale.yml
Labels: enhancement

#694 Add software partners
  docs/index.rst
  docs/source/software.rst
Labels: enhancement

#646 New contributing guidelines
  CONTRIBUTING.rst
  docs/conf.py
  docs/index.rst
  docs/source/developers.rst
Labels: enhancement

#705 Use the latest sphinx version for tests
  .ci_support/environment-notebooks.yml
  .ci_support/setup_miniconda.sh
  .ci_support/setup_pyiron.sh
  .ci_support/setup_upload.sh
  .ci_support/travis_build_docs.sh
  .ci_support/travis_build_notebooks.sh
  .ci_support/travis_setup_notebooks.sh
  .ci_support/travis_setup_pyiron.sh
  .travis.yml
  binder/environment.yml
  pyiron/gpaw/gpaw.py
Labels: enhancement
