Repository pyiron/pyiron, pull requests merged in 2020-07, with the labels that each got.

#758 maximum forces for the output added
  pyiron/atomistics/job/atomistic.py
Labels: enhancement

#749 Inputlist - 2nd try
  .ci_support/travis_test_backwards.sh
  .travis.yml
  pyiron/base/generic/inputlist.py
  pyiron/base/job/generic.py
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
  tests/backwards/test_sphinx_load.py
  tests/backwards/test_sphinx_save.py
  tests/base/generic/test_inputlist.py
  tests/sphinx/test_base.py
Labels: enhancement

#770 _spin_enabled changed to property
  notebooks/tests_sphinx_sphinx_check_all.ipynb
  pyiron/sphinx/base.py
Labels: bug, enhancement

#768 Get equivalent points
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#766 deleted get_equivalent_atoms
  pyiron/atomistics/structure/atoms.py
Labels: invalid

#771 Update save() function
  notebooks/tests_sphinx_sphinx_check_all.ipynb
  pyiron/base/job/generic.py
  pyiron/base/job/script.py
  pyiron/gpaw/pyiron_ase.py
Labels: enhancement

#772 Create deprecation warning
  CONTRIBUTING.rst
Labels: enhancement

#778 warning filters removed
  pyiron/sphinx/base.py
Labels: invalid

#776 :bug: Fix valence parser for elements starting with 'Z'
  pyiron/sphinx/base.py
Labels: bug

#783 sphinx version removed
  tests/sphinx/test_base.py
Labels: invalid

#784 import spglib directly
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/phonopy.py
  pyiron/sphinx/base.py
Labels: bug

#786 Simplify accessing the project directory for script jobs
  pyiron/base/job/external.py
  pyiron/base/project/generic.py
  pyiron/project.py
Labels: enhancement

#799 error when repeat gets a float
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: invalid

#785 time replaced by steps
  pyiron/lammps/base.py
  tests/lammps/test_base.py
Labels: bug, invalid

#801 number of electronic steps changed
  pyiron/dft/job/generic.py
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
  pyiron/vasp/base.py
  tests/sphinx/test_base.py
Labels: enhancement, invalid

#804 Add full_table parameter
  pyiron/base/database/filetable.py
Labels: bug

#805 update transfer_from_remote()
  pyiron/base/job/generic.py
Labels: enhancement

#806 Yaff cleanup: Mainly PEP8
  pyiron/quickff/quickff.py
  pyiron/yaff/yaff.py
  tests/yaff_module/test_yaff.py
Labels: enhancement

#787 Integration of pyscal with pyiron
  .ci_support/environment.yml
  .travis.yml
  pyiron/atomistics/job/atomistic.py
  pyiron/atomistics/structure/pyscal.py
  tests/atomistics/structure/test_pyscal.py
Labels: enhancement

#803 Implement delete_existing_job in create_job
  pyiron/base/job/generic.py
  pyiron/base/job/jobtype.py
  pyiron/base/project/generic.py
  pyiron/base/project/store.py
  pyiron/gpaw/pyiron_ase.py
  pyiron/interactive/scipy_minimizer.py
  pyiron/interactive/sxextoptint.py
  pyiron/project.py
  tests/testing/test_exampleJob.py
Labels: enhancement

#779 Consistency of codes + website
  pyiron/atomistics/job/atomistic.py
  pyiron/dft/job/generic.py
  pyiron/gaussian/gaussian.py
  pyiron/interactive/scipy_minimizer.py
  pyiron/interactive/sxextoptint.py
  pyiron/lammps/base.py
  pyiron/lammps/control.py
  pyiron/lammps/interactive.py
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
  pyiron/vasp/base.py
  pyiron/vasp/interactive.py
Labels: enhancement

#809 output/sphinx removed
  pyiron/sphinx/base.py
Labels: enhancement
