Repository pyiron/pyiron, pull requests merged in 2020-12, with the labels that each got.

#1236 Use new deprecate decorator
  pyiron/atomistics/job/interactivewrapper.py
  pyiron/atomistics/structure/atoms.py
  pyiron/lammps/base.py
  pyiron/vasp/potential.py
Labels: enhancement

#1244 [URGENT] ekt unit corrected
  pyiron/sphinx/base.py
  tests/sphinx/test_base.py
Labels: S/PHI/nX, bug, priority: critical

#1239 Remove redundant lines in LAMMPS input control
  pyiron/lammps/control.py
Labels: Lammps, code_smell, priority: low

#1250 Density of state implemented in SPHInX
  pyiron/dft/job/generic.py
  pyiron/sphinx/base.py
  tests/sphinx/test_base.py
  tests/static/sphinx/sphinx_test_2_5_hdf5/sphinx_test_2_5/eps.dat
Labels: S/PHI/nX, enhancement, priority: medium

#1257 Enable user defined LAMMPS scripts
  pyiron/lammps/base.py
Labels: enhancement

#1260 Neighbors norm order
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_neighbors.py
Labels: AtomisticStructure, enhancement, priority: low

#1265 update structure setter for interactive jobs
  pyiron/atomistics/job/atomistic.py
  pyiron/atomistics/job/interactive.py
  pyiron/testing/randomatomistic.py
Labels: AtomisticStructure, enhancement

#1230 Ever more detailed error messages
  pyiron/atomistics/job/sqs.py
  pyiron/gaussian/gaussian.py
  pyiron/gpaw/gpaw.py
Labels: enhancement, priority: low

#1263 restore set_check_overlap
  pyiron/sphinx/base.py
  tests/sphinx/test_base.py
Labels: S/PHI/nX, code_smell, priority: medium
