Repository pyiron/pyiron, pull requests merged in 2020-06, with the labels that each got.

#710 Add Sam's Sphinx test notebook to integration tests
  notebooks/tests_sphinx_sphinx_check_all.ipynb
Labels: enhancement

#709 forces missing in the list of interactive output tags
  pyiron/sphinx/interactive.py
Labels: enhancement, invalid

#717 Scriptjobs support input.json files
  pyiron/base/job/script.py
Labels: enhancement

#715 job status bugfix
  pyiron/base/job/jobstatus.py
Labels: bug

#721 New Error class
  pyiron/base/job/generic.py
  pyiron/dft/job/generic.py
  pyiron/gpaw/gpaw.py
  pyiron/sphinx/base.py
  pyiron/vasp/base.py
  tests/base/job/test_genericJob.py
  tests/sphinx/test_base.py
Labels: enhancement

#726 VASP: Remove redundant set_kopints() function
  pyiron/vasp/base.py
Labels: invalid

#727 External input
  pyiron/__init__.py
  pyiron/base/job/external.py
  pyiron/base/job/script.py
  pyiron/base/project/generic.py
Labels: enhancement

#730 Add logger to interactive interface
  pyiron/atomistics/job/interactive.py
  pyiron/interactive/sxextoptint.py
Labels: enhancement

#733 Fix deletion of named pipes
  pyiron/interactive/sxextoptint.py
Labels: bug

#735 Fix typo
  notebooks/tests_sphinx_sphinx_check_all.ipynb
  pyiron/base/job/generic.py
Labels: bug

#731 Job pipeline
  notebooks/pipeline.ipynb
  pyiron/atomistics/master/parallel.py
  pyiron/project.py
Labels: enhancement

#728 find_potential_file
  .ci_support/environment-notebooks.yml
  .ci_support/travis_setup_notebooks.sh
  binder/docker/Dockerfile
  binder/environment.yml
  binder/postBuild
  notebooks/bandstructure.ipynb
  notebooks/lammps-fe-c-example.ipynb
  notebooks/test_pyiron_installation.ipynb
  notebooks/water_MD.ipynb
  pyiron/atomistics/job/potentials.py
  pyiron/lammps/potential.py
  pyiron/sphinx/base.py
  pyiron/sphinx/potential.py
  pyiron/vasp/potential.py
Labels: enhancement

#725 VASP: updating write magmoms
  pyiron/vasp/base.py
  tests/vasp/test_vasp.py
Labels: bug

#723 VASP: update restart for magnetic calculations
  pyiron/vasp/base.py
Labels: bug

#739 Update Dokumentation for docker setup
  binder/docker/Dockerfile
  docs/source/installation.rst
Labels: enhancement

#740 small bugfix
  pyiron/sphinx/interactive.py
Labels: bug

#734 Try to fix SQLerror
  pyiron/base/settings/generic.py
Labels: bug, help wanted

#743 Update spin constraints
  pyiron/vasp/base.py
  tests/vasp/test_vasp.py
Labels: enhancement

#701 new input data structure closing #674
  pyiron/base/generic/inputlist.py
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
  tests/base/generic/test_inputlist.py
  tests/sphinx/test_base.py
Labels: enhancement

#756 Fix updated Sphinx Notebook
  notebooks/tests_sphinx_sphinx_check_all.ipynb
Labels: bug

#757 Github Code check
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#753 add utility scripts
  docs/index.rst
  docs/source/commandline.rst
  pyiron/base/job/generic.py
  pyiron/base/job/reloadfile.py
  pyiron/base/job/wrappercmd.py
  pyiron/base/settings/install.py
  pyiron/cli/__init__.py
  pyiron/cli/__main__.py
  pyiron/cli/install.py
  pyiron/cli/ls.py
  pyiron/cli/reloadfile.py
  pyiron/cli/rm.py
  pyiron/cli/wrapper.py
  setup.py
  tests/base/settings/test_install.py
Labels: enhancement
