Repository pyiron/pyiron, pull requests merged in 2020-10, with the labels that each got.

#1014 pyiron_base 0.1.19
  .ci_support/environment.yml
  .ci_support/travis_setup_notebooks.sh
  binder/postBuild
  setup.py
Labels: enhancement

#1013 Use read-only attribute of InputList
  pyiron/sphinx/base.py
Labels: enhancement

#1017 Fix Lammps pressure
  pyiron/lammps/control.py
Labels: bug

#1003 Extend get neighbors
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_neighbors.py
Labels: enhancement

#1021 Rename GpawJob to Gpaw
  notebooks/energy_volume_curve.ipynb
  notebooks/test_pyiron_installation.ipynb
  pyiron/__init__.py
  pyiron/gpaw/gpaw.py
Labels: enhancement

#1026 Docs cleanup
  docs/Makefile
  docs/make.bat
  docs/make.py
  docs/make.sh
  docs/make_apidoc.bat
Labels: enhancement

#1027 Update GPAW notebook
  notebooks/energy_volume_curve.ipynb
Labels: enhancement

#1031 PEP8 clean up for S/PHI/nX
  pyiron/sphinx/base.py
Labels: enhancement

#1032 Implement S/PHI/nX potential setter
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
Labels: enhancement

#1034 Test potential list
  tests/sphinx/test_base.py
  tests/vasp/test_vasp.py
Labels: enhancement

#1038 Update Error message - Sphinx JTH LDA
  pyiron/sphinx/potential.py
Labels: enhancement

#1037 Add delete_existing_job to create_table()
  pyiron/project.py
  tests/table/test_datamining.py
Labels: enhancement

#1015 Improve get neighbors
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_neighbors.py
Labels: bug, enhancement

#1023 Sqsjob polish
  .ci_support/environment.yml
  pyiron/atomistics/job/sqs.py
  tests/atomistics/job/test_sqs.py
Labels: enhancement

#1024 Installation documentation
  docs/source/installation.rst
Labels: enhancement

#1046 Find neighbors
  pyiron/atomistics/structure/neighbors.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_neighbors.py
Labels: bug, enhancement

#1051 Coarse run
  pyiron/interactive/sxextoptint.py
  pyiron/sphinx/base.py
  pyiron/sphinx/interactive.py
  tests/sphinx/test_interactive.py
Labels: enhancement

#1052 activation relaxation technique added
  pyiron/__init__.py
  pyiron/interactive/activation_relaxation_technique.py
  tests/interactive/test_activation_relaxation_technique.py
Labels: enhancement

#1056 lowered flush frequency
  pyiron/sphinx/interactive.py
  pyiron/vasp/interactive.py
Labels: code_smell

#1057 Get displacement
  pyiron/atomistics/job/atomistic.py
  tests/atomistics/job/test_atomistic.py
Labels: enhancement

#1058 Scipy minimiser updated
  pyiron/interactive/scipy_minimizer.py
  tests/interactive/test_scipyminimizer.py
Labels: enhancement

#1059 PEP8 clean up for interactive classes
  pyiron/interactive/activation_relaxation_technique.py
  pyiron/interactive/scipy_minimizer.py
  pyiron/interactive/sxextoptint.py
Labels: minor

#1065 Art name changed
  pyiron/__init__.py
  pyiron/interactive/activation_relaxation_technique.py
  tests/interactive/test_activation_relaxation_technique.py
Labels: minor

#1063 Attempt to fix issue related to using ASE atom
  pyiron/atomistics/job/interactivewrapper.py
Labels: bug

#1060 plotly added for structure plot
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
Labels: enhancement

#1072 Scipy
  pyiron/interactive/scipy_minimizer.py
  tests/interactive/test_scipyminimizer.py
Labels: enhancement

#1073 Separate plot
  pyiron/atomistics/structure/_visualize.py
  pyiron/atomistics/structure/atoms.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_visualize.py
Labels: enhancement

#1061 Store structure in SQS job
  pyiron/atomistics/job/sqs.py
Labels: bug

#1064 Structures: Write CIF files manually
  notebooks/structures.ipynb
Labels: enhancement

#1068 Fix interactive mode for GPAW
  pyiron/gpaw/gpaw.py
  pyiron/gpaw/pyiron_ase.py
Labels: bug

#1069 Remove docker builds
  .travis.yml
  binder/docker/Dockerfile
  binder/docker/deploy.sh
Labels: enhancement

#1078 Add tests for GPAW
  tests/gpaw/__init__.py
  tests/gpaw/test_gpaw.py
Labels: enhancement

#1081 Add analyse_ovito_diamond()
  pyiron/atomistics/structure/ovito.py
Labels: enhancement

#1086 Implement unit test for selective dynamics
  pyiron/atomistics/structure/atoms.py
  pyiron/thermodynamics/hessian.py
  tests/atomistics/structure/test_atoms.py
Labels: bug

#1087 Implement interactive_pressures_getter() for ASE jobs
  pyiron/gpaw/pyiron_ase.py
Labels: enhancement

#1092 ScipyMinimize: Set status to finished at the end of run_static()
  pyiron/interactive/scipy_minimizer.py
Labels: bug

#1096 Update to pyiron_base 0.1.23
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#1098 Fix plot3d
  pyiron/atomistics/structure/atoms.py
Labels: bug

#1099 Simplify logic
  pyiron/lammps/control.py
  tests/lammps/test_control.py
Labels: enhancement

#1103 fix sqs publication
  pyiron/atomistics/job/sqs.py
Labels: enhancement

#1101 add primitive matrix to phonopyJob
  pyiron/atomistics/master/phonopy.py
Labels: enhancement

#1100 change pressure tolerance
  pyiron/interactive/scipy_minimizer.py
Labels: enhancement

#1107 Condition if no unoccupied states are there
  pyiron/vasp/outcar.py
  tests/static/vasp_test_files/outcar_samples/OUTCAR_2
  tests/vasp/test_outcar.py
Labels: bug

#1110 Increase ase requirement
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#1111 Fix periodic boundaries for ASE 3.20
  pyiron/gpaw/pyiron_ase.py
Labels: bug

#1113 Reduce dependencies
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#1112 Update to pyiron_base 0.1.24
  .ci_support/environment.yml
  setup.py
Labels: enhancement

#1114 Implement kpoint_mesh property
  pyiron/dft/job/generic.py
  pyiron/gpaw/gpaw.py
  pyiron/sphinx/base.py
  pyiron/vasp/base.py
Labels: enhancement

#1115 Restructure ASE interface
  pyiron/atomistics/job/interactive.py
  pyiron/gpaw/gpaw.py
  pyiron/gpaw/pyiron_ase.py
Labels: bug

#1119 Murnaghan: enforce num_points to be integer
  pyiron/atomistics/master/murnaghan.py
Labels: enhancement

#1123 Add camera option to animate_structure as in plot3d
  pyiron/atomistics/job/atomistic.py
Labels: enhancement

#1122 Fix Lammps Logfile location
  pyiron/lammps/interactive.py
Labels: Lammps, enhancement

#1091 Spin resolved values of the electronic structure
  pyiron/dft/job/generic.py
  pyiron/dft/waves/dos.py
  pyiron/dft/waves/electronic.py
  pyiron/sphinx/base.py
  pyiron/vasp/base.py
  pyiron/vasp/vasprun.py
  tests/dft/waves/test_dos.py
  tests/dft/waves/test_electronic.py
  tests/vasp/test_vasp_import.py
  tests/vasp/test_vasprun.py
Labels: VASP, enhancement

#1127 Add CODEOWNERS
  .github/CODEOWNERS
Labels: enhancement
