Repository pyiron/pyiron, pull requests merged in 2021-01, with the labels that each got.

#1240 Shift analyze related stuff to the new analyze class
  pyiron/atomistics/structure/analyse.py
  pyiron/atomistics/structure/atoms.py
  pyiron/atomistics/structure/pyscal.py
  pyiron/table/funct.py
  pyiron/thermodynamics/interfacemethod.py
  tests/atomistics/structure/test_analyse.py
  tests/atomistics/structure/test_atoms.py
  tests/atomistics/structure/test_pyscal.py
Labels: AtomisticStructure, priority: low

#1280 separate string
  pyiron/sphinx/base.py
Labels: S/PHI/nX, priority: low

#1285 prevent mirror when maximum value is negative
  pyiron/atomistics/structure/_visualize.py
Labels: AtomisticStructure, bug, priority: medium
